# Generated by Django 3.1 on 2020-08-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200824_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
