# Generated by Django 3.1 on 2020-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200821_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/static/images/'),
        ),
    ]
