# Generated by Django 3.1 on 2020-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200824_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
    ]
